version: "3.9"
services:
  bot:
    restart: unless-stopped
    build: .
  lavalink:
    image: "fredboat/lavalink:master-v3.3.2.3"
    command: --network host
    ports:
    - "8080:8080"
    volumes:
    - type: bind
      source: ./application.yml
      target: /opt/Lavalink/application.yml
