name: CI

on:
  push:
    branches: [dev]

jobs:
  deploy:
    name: Deploy
    runs-on: [ubuntu-latest]
    steps:
    - name: ssh deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.REMOTE_KEY }}
        port: 22
        script: |
          mkdir -p ${{ secrets.REMOTE_PROJECT_PATH }}
          cd ${{ secrets.REMOTE_PROJECT_PATH }}
          git pull origin master
          docker-compose up --no-start
          docker-compose restart