name: CI

on:
  push:
    branches: [master]

jobs:
  deploy:
    name: Deploy
    runs-on: [ubuntu-latest]
    steps:
    - name: ssh deploy
      uses: easingthemes/ssh-deploy@v2.1.5
      env:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.REMOTE_KEY }}
        port: 22
        script: |
          mkdir -p ${{ secrets.REMOTE_PROJECT_PATH }}
          cd ${{ secrets.REMOTE_PROJECT_PATH }}
          git pull origin master
          docker-compose restart